### ISSUE TITLE
Running Emcee locally

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [avito-tech/Emcee#14]
Hi is there a working CLI example for running Emcee locally, also some Docs might useful with different examples, I did have a look at the wiki but I am still unsure how to run the tool. 

Also, this might be useful for getting the list of tests  https://github.com/dropbox/hypershard-ios

**Comment by beefon** [comment]
Hey!

Thanks for suggesting the hypershard. Although it is possible to parse sources, Emcee does not require them to run tests. It is easier to distribute build artifacts with integrated runtime support than checking out a repository.

As of running Emcee, currently I agree that the setup is not very user friendly. A lot of stuff must be provided explicitly. 


1. To run on CI or locally, invoke Emcee in "client" mode: use `runTestsOnRemoteQueue` command.
1. It will deploy _itself_ to a provided queue host (`--queue-server-destination`) and start it remotely over SSH with `startLocalServer` command. If the queue is already running, it won't start the new queue instance.
1. Queue will then go over its config file and deploy workers over SSH and start them using `distWork` command. Workers will talk to the queue over REST.
1. Then, client will talk over REST to the newly started queue. It will schedule tests (under your job id `--run-id`) to the queue, and poll it for results.

```shell
$ Emcee runTestsOnRemoteQueue \ 
      --queue-server-destination shared_queue_deployment_destinations.json \
      --queue-server-run-configuration-location http://example.com/queue_config.zip#config.json \
      --run-id JOB_ID \
      --test-arg-file /path/to/testargfile.json \
      --temp-folder /path/to/temp_folder \
      --emcee-version "400"
```

- `--queue-server-destination` — is a _local_ JSON file with array of [`DeploymentDestination` models](https://github.com/avito-tech/Emcee/blob/master/Sources/Deployer/DeploymentDestination.swift) - pass an array with single object. [More details here](https://github.com/avito-tech/Emcee/wiki/Deployment-Destination).
- `--queue-server-run-configuration-location` — is a _remote_ ZIP with JSON file, which content is described by [`QueueServerRunConfiguration`](https://github.com/avito-tech/Emcee/blob/master/Sources/LocalQueueServerRunner/QueueServerRunConfiguration.swift) model. [Model details about that here](https://github.com/avito-tech/Emcee/wiki/Queue-Server-Run-Configuration).
- `--run-id` — name your job with tests, e.g. `$(uuidgen)` ;)
- `--test-arg-file` — a _local_ JSON file with a test plan. You'll have to pass URLs to build artifacts and so on. This file describes your job. You can [look at the sources](https://github.com/avito-tech/Emcee/blob/master/Sources/TestArgFile/TestArgFile.swift) and then [read the docs](https://github.com/avito-tech/Emcee/wiki/Test-Arg-File).
- `--temp-folder` — local temp folder for Emcee
- `--emcee-version` — version, this is rather a hack to synchronize emcee version on our CI with commit hash (we version by commit not by tag). I have a plan to remove this/make optional.

**Comment by beefon** [comment]
# Examples

## `--queue-server-destination` - this describes where you want to start queue server

```json
[
    {
        "host": "ios-builder-99.sky.co.uk",
        "password": "ssh_password",
        "port": 22,
        "remote_deployment_path": "/Users/ssh_username/remote_ui_tests.noindex/",
        "username": "ssh_username"
    }
]
```

## `--queue-server-run-configuration-location` - queue config

Sample value:
http://artifactory.sky.co.uk/artifactory/queue_server_run_configuration.json.generated.56b992ee-7125-11ea-84ce-f01898f1c923.artifact.zip#queue_server_run_configuration.json

Sample contents:

In a root of ZIP file, `queue_server_run_configuration.json`:

```json
{
    "analyticsConfiguration": {},
    "checkAgainTimeInterval": 30,
    "deploymentDestinationConfigurations": [
        {
            "destinationIdentifier": "ios-builder-01.sky.co.uk",
            "numberOfSimulators": 4
        },
        {
            "destinationIdentifier": "ios-builder-02.sky.co.uk",
            "numberOfSimulators": 4
        }
    ],
    "queueServerTerminationPolicy": {
        "caseId": "afterBeingIdle",
        "period": 3600
    },
    "reportAliveInterval": 30,
    "workerDeploymentDestinations": [
        {
            "host": "ios-builder-01.sky.co.uk",
            "password": "ssh_password",
            "port": 22,
            "remote_deployment_path": "/Users/ssh_username/remote_ui_tests.noindex/",
            "username": "ssh_username"
        },
        {
            "host": "ios-builder-02.sky.co.uk",
            "password": "ssh_password",
            "port": 22,
            "remote_deployment_path": "/Users/ssh_username/remote_ui_tests.noindex/",
            "username": "ssh_username"
        }
    ]
}
```
## `--test-arg-file`, your test plan

```json
{
    "entries": [
        {
            "testsToRun": [
                {
                    "predicateType": "allProvidedByRuntimeDump"
                }
            ],
            "testDestination": {
                "deviceType": "iPhone 7",
                "runtime": "11.4"
            },
            "numberOfRetries": 0,
            "environment": {},
            "testType": "uiTest",
            "buildArtifacts": {
                "xcTestBundle": {
                    "location": "http://.../FunctionalTests-Runner.app.artifact.zip#FunctionalTests-Runner.app/PlugIns/FunctionalTests.xctest",
                    "runtimeDumpKind": "logicTest"
                },
                "additionalApplicationBundles": [],
                "runner": "http://.../FunctionalTests-Runner.app.artifact.zip#FunctionalTests-Runner.app",
                "appBundle": "http://.../Avito.app.artifact.zip#Avito.app"
            },
            "testRunnerTool": {
                "toolType": "fbxctest",
                "fbxctestLocation": "http://.../fbxctest_20200319T225817.zip"
            },
            "simulatorControlTool": {
                "toolType": "fbsimctl",
                "location": "http://.../fbsimctl_20200319T225817.zip"
            },
            "simulatorOperationTimeouts": {
                "create": 30,
                "boot": 180,
                "delete": 20,
                "shutdown": 20,
                "automaticSimulatorShutdown": 60,
                "automaticSimulatorDelete": 300
            },
            "developerDir": {
                "kind": "useXcode",
                "CFBundleShortVersionString": "11.3.1"
            },
            "scheduleStrategy": "progressive",
            "simulatorSettings": {
                "simulatorLocalizationSettings": {
                    "localeIdentifier": "en_US",
                    "keyboards": [
                        "en_US@sw=QWERTY;hw=Automatic"
                    ],
                    "passcodeKeyboards": [
                        "en_US@sw=QWERTY;hw=Automatic"
                    ],
                    "languages": [
                        "en"
                    ],
                    "addingEmojiKeybordHandled": true,
                    "enableKeyboardExpansion": true,
                    "didShowInternationalInfoAlert": true
                },
                "watchdogSettings": {
                    "bundleIds": [],
                    "timeout": 150
                }
            },
            "testTimeoutConfiguration": {
                "singleTestMaximumDuration": 360,
                "testRunnerMaximumSilenceDuration": 360
            },
            "pluginLocations": []
        }
    ],
    "priority": 0,
    "testDestinationConfigurations": [
        {
            "testDestination": {
                "deviceType": "iPhone 7",
                "runtime": "11.4"
            },
            "reportOutput": {
                "junit": "tests-artifacts/iphone_7_ios_114.xml",
                "tracingReport": "tests-artifacts/iphone_7_ios_114.trace"
            }
        }
    ]
}
```

`reportOutput` paths are local, on machine where you execute `Emcee runTestsOnRemoteQueue`.

**Comment by beefon** [comment]
Also, there is no "local" way of running Emcee. This will be similar to running a modern version of `xcodebuild`. Emcee requires to run it as if you'd use it on build farm, even if you only have a single computer. Same machine can worker as a queue and a worker.

**Comment by Ashraf-Ali-aa** [comment]
@beefon thanks for you help it might be worth creating a guided CLI tool to set up the project like https://github.com/Subito-it/Mendoza `mendoza configuration init`

**Comment by beefon** [comment]
Thanks for suggestion, we will consider adding this, and we also want to minimize a number of required things to start using Emcee by replacing them with some default values.

**Comment by beefon** [comment]
We've quickly implemented a test discovery without runtime dump, you can read more here. Thanks for suggesting an idea!

https://github.com/avito-tech/Emcee/releases/tag/v6.0.0

**Comment by Ashraf-Ali-aa** [comment]
@beefon you might run into this issue which is also in bluepill - https://github.com/linkedin/bluepill/issues/352

**Comment by beefon** [comment]
Indeed, but we found this to be better than running runtime logic for 50 test bundles.
We still use runtime to discover UI and application tests because that allows to include some meta info about each test.
So if the problems described in bluepill issue will happen, an alternative approach is always available.

**Comment by beefon** [comment]
I'm closing this issue now.
