### ISSUE TITLE
SPM does not see brew deps

### ISSUE THREAD

**Issue by gopito** [avito-tech/Emcee#16]
Hello. Have you managed to fix it?
I have the same problem).
https://forums.swift.org/t/xcode-11-4b3-spm-does-not-see-brew-deps/34307

**Comment by gopito** [comment]
libssh2 is dependent of openssl.
After brew reinstall openssl
You will see:
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
/usr/local/etc/openssl@1.1/certs

and run
/usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

I have managed to build with:
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" && \
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" && \
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig" && \
swift build

**Comment by beefon** [comment]
Hey, I didn't manage to fix this, but thanks a lot for updating with solution!

**Comment by beefon** [comment]
The fix for Xcode 11.4 has been landed here: https://github.com/avito-tech/Emcee/commit/c492cea6f6c6e502893c0fa826d6e1e28173f858

So I'm closing this issue.
