### ISSUE TITLE
[Wiki] Cache page outdated

### ISSUE THREAD

**Issue by EvgenyIv96** [avito-tech/Emcee#30]
Wiki page: https://github.com/avito-tech/Emcee/wiki/Cache#file-cache

Both links to the configuration file and example at the bottom of the page are invalid:
https://github.com/avito-tech/Emcee/blob/master/Sources/RuntimeDump/RuntimeDumpRemoteCache/Models/RuntimeDumpRemoteCacheConfig.swift
https://github.com/avito-tech/Emcee/blob/master/Tests/RuntimeDumpTests/RuntimeDumpRemoteCacheConfigTests.swift

**Comment by beefon** [comment]
Fixed, thanks!
