### ISSUE TITLE
[Wiki] Simulator Settings page is outdated

### ISSUE THREAD

**Issue by EvgenyIv96** [avito-tech/Emcee#33]
link - https://github.com/avito-tech/Emcee/wiki/Simulator-Settings

`simulatorKeychainSettings` object missed:

`simulatorKeychainSettings`
This object describes what the settings apply to the  keychain. This is _optional_ field, you will need it only when you want to apply some settings to the keychain.

- `rootCerts` array of locations of the certificates which will be added to the trusted root store into keychain.

Also I think JSON Example (https://github.com/avito-tech/Emcee/wiki/Simulator-Settings#complete-json-example) should be updated or there should be a few examples - one without `simulatorKeychainSettings` and second with `simulatorKeychainSettings`:
````
{
    "simulatorSettings": {
        "simulatorLocalizationSettings": {
            "localeIdentifier": "ru_US",
            "keyboards":  ["ru_RU@sw=Russian;hw=Automatic", "en_US@sw=QWERTY;hw=Automatic"],
            "passcodeKeyboards": ["ru_RU@sw=Russian;hw=Automatic", "en_US@sw=QWERTY;hw=Automatic"],
            "languages": ["ru-US", "en", "ru-RU"],
            "addingEmojiKeybordHandled": true,
            "enableKeyboardExpansion": true,
            "didShowInternationalInfoAlert": true,
            "didShowContinuousPathIntroduction": true
        },
        "simulatorKeychainSettings": {
            "rootCerts": ["http://example.com/cert.zip#cert.pem"]
        },
        "watchdogSettings": {
            "bundleIds": ["sample.app"],
            "timeout": 42
        }
    }
}
````

**Comment by beefon** [comment]
Done, thanks!
Regarding the `simulatorKeychainSettings` example: this field is optional and I think there is no need to show that this field can be omitted.
