### ISSUE TITLE
[Wiki] Queue Server Destination page is outdated

### ISSUE THREAD

**Issue by EvgenyIv96** [avito-tech/Emcee#35]
link - https://github.com/avito-tech/Emcee/wiki/Queue-Server-Destination

1) First link to the DeploymentDestination.swift is invalid

> This file is described by DeploymentDestination.swift source file.

2) No information about `workerId` field for the Queue Server Destination on this page. In the example ([link](https://github.com/avito-tech/Emcee/wiki/Queue-Server-Configuration#queueserverdeploymentdestination)) no `workerId` field provided.

**Comment by beefon** [comment]
That page has been deleted entirely.
