### ISSUE TITLE
[Wiki] Queue Server Configuration page. Incorrect info in `workerSpecificConfigurations` section.

### ISSUE THREAD

**Issue by EvgenyIv96** [avito-tech/Emcee#37]
section link - https://github.com/avito-tech/Emcee/wiki/Queue-Server-Configuration#workerspecificconfigurations

Here is said
> This is map from worker id to Worker Specific Configuration object.

But it doesn't work in this way. 
There should be map from `host` to Worker Specific Configuration object cause `workerId` ignored and it always equals to `host` value.

Also no info about ignored `workerId` value on the 'Deployment Destination' page (https://github.com/avito-tech/Emcee/wiki/Deployment-Destination#workerid-string)

discussion: https://t.me/emcee_ios/540, https://t.me/emcee_ios/542

**Comment by beefon** [comment]
Thanks, I've updated docs to make it clearer that worker id == hostname as of now.
https://github.com/avito-tech/Emcee/wiki/Deployment-Destination
