### ISSUE TITLE
[Wiki] Resources URLs notes.

### ISSUE THREAD

**Issue by EvgenyIv96** [avito-tech/Emcee#38]
Emcee now supports authentication headers and no information about it provided in wiki.

I suggest to add this information on the pages listed below:
- Home page. Below `runTestsOnRemoteQueue` command - [link](https://github.com/avito-tech/Emcee/wiki#using-emcee)
- Test Arg File page. Below build artifacts examples - [link](https://github.com/avito-tech/Emcee/wiki/Test-Arg-File#buildartifacts)
- Test Arg File page. Below plugins locations example - [link](https://github.com/avito-tech/Emcee/wiki/Test-Arg-File#pluginlocations)
- Simulator Settings page. Below rootCerts locations example - [link](https://github.com/avito-tech/Emcee/wiki/Simulator-Settings#simulatorkeychainsettings)

Note text:
> Note that URLs to ZIP archive contain reference to the files in the archives. In fact this URLs are `ResourceLocation` entities. HTTP authentication headers supported. Read more on [URL Handling](https://github.com/avito-tech/Emcee/wiki/URL-Handling) page.

**Comment by beefon** [comment]
> no information about it provided in wiki

Actually URL handling page gives an [example](https://github.com/avito-tech/Emcee/wiki/URL-Handling)

**Comment by beefon** [comment]
I've added this note to all but main page. I want to re-write it and include your tutorial on it.

*Important note about URLs:* any URL to any ZIP archive is expected to contain a reference to a file inside that archive. In fact, this URL is `ResourceLocation` entities. It is possible to append arbitrary HTTP headers as well, including for authentication. Please read more on [URL Handling](https://github.com/avito-tech/Emcee/wiki/URL-Handling) page.
