### ISSUE TITLE
[Wiki] Deployment Destination page. Missing important info about authentication by key.

### ISSUE THREAD

**Issue by EvgenyIv96** [avito-tech/Emcee#39]
section link - https://github.com/avito-tech/Emcee/wiki/Deployment-Destination#authentication-object

Emcee supports authentication by key but there is no info about the need of the public key:
If you set path for private key like that: `{"authentication": {"keyPath": "/Users/builder/keys/id_rsa"}}`
To get authentication works you must have both private and public keys at paths:
- (private) `/Users/builder/keys/id_rsa`
- (public) `/Users/builder/keys/id_rsa.pub`

If you haven't public key at path `/Users/builder/keys/id_rsa.pub` Emcee will stuck on the authentication step with message:
> Enter passphrase for ... :

This is how **libssh2** works and it needs both private and public keys at the same path

discussion: https://t.me/emcee_ios/495, https://t.me/emcee_ios/498, https://t.me/emcee_ios/499, https://t.me/emcee_ios/500, https://t.me/emcee_ios/501

**Comment by beefon** [comment]
Thanks a lot, updated [docs page](https://github.com/avito-tech/Emcee/wiki/Deployment-Destination#authentication-object)
