### ISSUE TITLE
[Wiki] Missing getting started document

### ISSUE THREAD

**Issue by EvgenyIv96** [avito-tech/Emcee#40]
When I started trying to run tests using Emcee I've spend a lot of time to understand where to start and what do I need to do to make it works.
So it would be good to have common 'Getting started' document like this:

1. Build Emcee binary 
	- `git clone https://github.com/avito-tech/Emcee.git`
	- `cd Emcee`
	- `make build`
	- binary will be into `.build/debug/Emcee` - `Emcee` file
2. Prepare file server (https://github.com/avito-tech/Emcee/wiki/Organizing-HTTP-server)
3. Prepare machines: setup ssh authentication, install `Xcode` and `libssh2` (https://github.com/avito-tech/Emcee#libssh2)
4. Generate `queue_server_configuration.json` and upload it to the file server (https://github.com/avito-tech/Emcee/wiki/Queue-Server-Configuration)
5. Upload Emcee binary to the file server
6. Start writing **CI code** by getting Emcee binary
	- `wget -O Emcee http://example.com/binary/Emcee`
	- `chmod +x Emcee`
7. Write code to build your project using `xcodebuild` command
8. Write code to extract `xctest` bundle from app (https://github.com/avito-tech/Emcee/wiki/Build-Artifacts-and-Test-Types)
9. Write code to archive and upload build artifacts to the file server
10. Write code to generate `testargfile.json` for Emcee without tests array (to make runtime dump of the test bundle using Emcee) (https://github.com/avito-tech/Emcee/wiki/Test-Arg-File)
11. Write code to get all tests from `xctest` bundle using `Emcee dump` command (https://github.com/avito-tech/Emcee/wiki/Runtime-Dump)
12. Write code to create array of tests to test using Emcee
13. Write code to generate `testargfile.json` for Emcee (https://github.com/avito-tech/Emcee/wiki/Test-Arg-File)
14. Write code to run tests on Emcee using `Emcee runTestsOnRemoteQueue` command

**Comment by beefon** [comment]
Brilliant! Thanks for doing this! I've created [this page](https://github.com/avito-tech/Emcee/wiki/Getting-Started) and added reference to it from Home.
