### ISSUE TITLE
Runtime dump did not create a JSON file at expected location

### ISSUE THREAD

**Issue by Naarneck** [avito-tech/Emcee#6]
Hi guys,
I have an error when trying to execute _runTests_:

`[ERROR] 2019-02-06 15:41:40.727+0200 AvitoRunner[60201]: Runtime dump did not create a JSON file at expected location: '~/tempfolder/TemporaryDirectory.nEQvIR/runtime_tests.json'.`

My config looks like this (i've deleted original path for reasons):
```
~/emcee/.build/x86_64-apple-macosx10.10/debug/AvitoRunner runTests \
--fbsimctl "https://github.com/beefon/FBSimulatorControl/releases/download/avito0.0.1/fbsimctl_20180831T142903.zip" \
--fbxctest "https://github.com/beefon/FBSimulatorControl/releases/download/avito0.0.1/fbxctest_20180831T142535.zip" \
--junit "$(pwd)/test-results/junit.alldestinations.xml" \
--trace "$(pwd)/test-results/trace.alldestinations.json" \
--number-of-retries 1 \
--number-of-simulators 2 \
--app "~/build/Build/Products/Debug Fast-iphonesimulator/MyApp.app" \
--runner "~/build/Build/Products/Debug Fast-iphonesimulator/MyApp UI Tests-Runner.app" \
--xctest-bundle "~/build/Build/Products/Debug Fast-iphonesimulator/MyApp UI Tests.xctest" \
--schedule-strategy "individual" \
--single-test-timeout 100 \
--temp-folder "$(pwd)/tempfolder" \
--test-destinations "destination_iphone_se_ios103.json"
```
Also I have some issues with URL path, maybe it is related. Some argumentss contains space characters and it seems like we have same validation for local path and URL path and this cause problem when validating URLs. It would be nice to add some space character handler 

I've tried to modify function _ResourceLocation.swift_ in this way:
```
    public static func from(_ string: String) throws -> ResourceLocation {
        let preparedString = string.replacingOccurrences(of: " ", with: "%20", options: .literal, range: nil)
        guard var components = URLComponents(string: preparedString) else { throw ValidationError.cannotCreateUrl(preparedString) }
        if components.scheme == nil {
            components.scheme = "file"
        }
        guard let url = components.url else { throw ValidationError.cannotCreateUrl(string) }
        if url.isFileURL {
            return try withPathString(string)
        } else {
            return withUrl(url)
        }
    }
```
It helped, but I stuck at JSON file error.

Thanks for any suggestions, probably I just missed something.
The project looks so cool by the way.

**Comment by beefon** [comment]
Hi @Naarneck , thanks for great feedback. If you wish, feel free to create a PR to fix spaces in path issue. Let me know if want me to fix that instead!

Regards the JSON file issue, runtime dump requires some integration. I wonder if you have supported it in your test target. 
There is a short note about how does runtime dump work and what can you do to make it work with your project [here](https://github.com/avito-tech/Emcee/tree/master/Sources/RuntimeDump).
Also, there is our implementation that we currently use in Avito [here](https://github.com/avito-tech/Emcee/tree/master/TestApp/TestAppUITests/RuntimeDump), with appropriately updated Info.plist [here](https://github.com/avito-tech/Emcee/blob/master/TestApp/TestAppUITests/Info.plist#L22).
Let me know if that helps! If it still does not work, you could attempt to trace the issue in the debugger by removing [this check](https://github.com/avito-tech/Emcee/blob/master/TestApp/TestAppUITests/RuntimeDump/PrincipalClass.swift#L14) from your principal class (e.g. maybe it actually finds all classes but env is not set, or vice versa) or you can check out more logs, Emcee prints detailed log location when you invoke it.

**Comment by beefon** [comment]
@Naarneck , I've merged the [fix for spaces in paths](https://github.com/avito-tech/Emcee/commit/616b152466983913f74b81e0b2c50d3cca2ec53e). Feel free to try it out!
You can also swift to the recent fbxctest/fbsimctl prebuilt binary URLs:
https://github.com/beefon/FBSimulatorControl/releases

**Comment by beefon** [comment]
I'm going to close this issue, feel free to report it again if you experience it.

**Comment by magicalc0der** [comment]
I am getting the same error even if I try to use `testApp.app` that is supplied in the same repo and has PincipalClass set. The command I use looks as it follows:

```
./.build/x86_64-apple-macosx10.10/debug/AvitoRunner runTests \
--fbsimctl "https://github.com/beefon/FBSimulatorControl/releases/download/0.0.3/fbsimctl_20190208T125742.zip" \
--fbxctest "https://github.com/beefon/FBSimulatorControl/releases/download/0.0.3/fbxctest_20190208T125921.zip" \
--junit "$(pwd)/test-results/junit.alldestinations.xml" \
--trace "$(pwd)/test-results/trace.alldestinations.json" \
--number-of-retries 1 \
--number-of-simulators 2 \
--app "/Users/test/projects/testApp/build/testApp/Build/Products/Debug-iphonesimulator/testApp.app" \
--runner "/Users/test/projects/testApp/build/testApp/Build/Products/Debug-iphonesimulator/testAppUITests-Runner.app" \
--xctest-bundle "/Users/test/projects/testApp/build/testApp/Build/Products/Debug-iphonesimulator/testAppUITests-Runner.app/PlugIns/testAppUITests.xctest" \
--schedule-strategy "individual" \
--single-test-timeout 100 \
--temp-folder "$(pwd)/tempfolder" \
--test-destinations "destination_iphone_se_ios103.json"
```

and the error message is 

> [ERROR] 2019-03-08 08:23:00.071+0000 AvitoRunner[93804]: Attempt 5 of 5, got an error: Runtime dump did not create a JSON file at expected location: '/Users/test/projects/github/Emcee/tempfolder/TemporaryDirectory.OKpZ3h/runtime_tests.json'.

**Comment by beefon** [comment]
@magicalc0der I wonder if you have iOS 10.3.1 simulator installed in your Xcode?
