### ISSUE TITLE
Запуск на девайсах

### ISSUE THREAD

**Issue by mklinkov** [avito-tech/Emcee#8]
Добрый день!

Подскажите, позволяет ли тулза запускать тесты на устройствах, можно ли на ее основе сделать ферму?

**Comment by beefon** [comment]
Здравствуйте, к сожалению, пока только симуляторы. Девайсы пока нет в планах реализовывать.

**Comment by mklinkov** [comment]
Спасибо за ответ!

**Comment by mklinkov** [comment]
Думаю, рановато закрыл вопрос) а этот функционал не реализован из-за какой-то конкретной проблемы? или просто пока как не приоритетный?

**Comment by beefon** [comment]
Он не в приоритете. Проблема тоже есть: идут работы по отказу от fbxctest. По окончанию перехода на xcodebuild можно будет думать о возможности запуска на устройствах, но там приличный пласт работ потребуется: как минимум нужно будет сделать какой-то дискавери подключенных устройств на воркерах, очередь должна будет драйвить то, кому какие тесты она отдает. Сейчас логика простая - симулятор освободился, просим следующий тест (любой фактически). С реальными устройствами такое не проканает, нужна специфика - тест под iPhone7,2 с iOS 11, например.

**Comment by mklinkov** [comment]
Да, проблема понятна. Сейчас просто заняты поиском решений, под наши потребности и критичным является запуск на девайсах, так как в задании есть проверка отзывчивости в различных кейсах, симулятор не дает полноценно такие вещи проверять.

**Comment by beefon** [comment]
Посмотрите на idb, там вроде есть запуск на устройствах.

**Comment by mklinkov** [comment]
спасибо!

**Comment by artyom-razinov** [comment]
Внесу свои 5 копеек. Мы ресерчили этот вопрос и реально решили осознанно не делать запуск на девайсах. Сейчас у нас около 70 тачек для самых разных нужд с хорошим планом по наращиванию мощностей. И мы их используем и для CI билдов (там что-то около 16 штук на PR и около 100 по iOS части). Фактически мы получаем бесплатно штук 200 симуляторов для тестов. Чтобы получить то же самое по мощностям, надо закупать 200 девайсов каждого типа и постоянно при обновлениях девайсов их менять. Это очень дорого просто для покупки - это раз. Еще нужно как-то эти сотни девайсов поддерживать в работоспособном состоянии, охлаждать (сейчас они работают без отдыха в течение долгого времени, где-то на вскидку 40% суток загружены на полную), бутить/ребутить, кликать, чистить стейт. Разрабатывать способы обхода ограничений iOS - на симуляторах их нет, мы можем прямо в файловую систему компа писать все что угодно.

Это я к тому, что стоит задуматься о тестировании на девайсах. Так-то у нас есть планы в виде фантазий по перформанс тестированию на девайсах, но это трудозатратно, так что мы ничего не делали в этом плане и в ряд ли в ближайшее время будем делать.

**Comment by mklinkov** [comment]
Да, я понимаю сложность и стоимость такой системы, пока задача выглядит именно с учетом запуска тестов на девайсах.
Ну кроме того, это просто интересный кейс который хочется решить))
